INSERT INTO beneficio (descripcion, descuento) VALUES
('Descuento en plan mensual de entrenamiento', 10.0),
('Promoción de nutrición personalizada', 15.0),
('Acceso gratuito a evaluación física inicial', 100.0),
('Paquete de bienvenida con productos saludables', 5.0),
('Sesión de entrenamiento personalizada gratis', 100.0),
('Descuento por traer un amigo', 20.0),
('Mes gratis por suscripción anual', 100.0),
('Acceso a contenido exclusivo en línea', 8.0),
('Consulta nutricional de seguimiento sin costo', 100.0),
('Descuento en tienda de suplementos', 12.0),
('Cuota de inscripción gratis', 100.0),
('Descuento por pago anticipado de 6 meses', 18.0),
('Plan familiar con tarifa reducida', 25.0),
('Acceso ilimitado a clases grupales', 100.0);
